#!/bin/sh

CURDIR=`dirname "$0"`

cp ${NSLS_DIR}/db/nsls.json ${CURDIR}/../shortlog/
cd ${CURDIR}/../shortlog

git config user.name "${USER_NAME}"
git config user.email "${USER_EMAIL}"

git pull
git add nsls.json
git commit -m "shortlog: automatic update by admin script"
git push
